# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 5.2.0
_src_path: https://github.com/epics-containers/deployment-template-argocd
argocd_cluster: argus
argocd_server: argocd.diamond.ac.uk
cluster_name: argus
cluster_namespace: kgv66629
deployment_repo: https://github.com/tomkane-dls/t01-deployment
description: t01 IOC Instances and Services Deployment Repository for Argo CD
domain: t01
git_platform: github.com
github_org: tomkane-dls
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
services_release: main
services_repo: https://github.com/tomkane-dls/t01-services
